name: Build All Modes
permissions:
    contents: write
    pull-requests: write # For adding comments to PR.
on:
  pull_request:
    branches:
        - 'main'
    paths-ignore:
        - 'README.md'
        - 'docs/**'
        - 'docs-export/**'

jobs:
  calculate_matrix:
    name: Calculate job matrix
    runs-on: windows-2022
    outputs:
      jobs: ${{ steps.jobs.outputs.jobs }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0 # needed to get commits since last tag
          token: ${{ secrets.UEPSEUDO_PAT }}
      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1.13.0

      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
      - name: Calculate the CI job matrix
        run: |
          $modes = (xmake ci --dump=modes)
          echo "jobs=$modes" >> $env:GITHUB_OUTPUT
        id: jobs
        shell: pwsh
  build:
    name: ${{ matrix.mode }}
    needs: [ calculate_matrix ]
    strategy:
      fail-fast: false
      matrix: 
        mode: ${{ fromJSON(needs.calculate_matrix.outputs.jobs) }}
        include:
          - mode: "Game__Shipping__Win64"
            artifact: true
          - mode: "Game__Debug__Win64"
            artifact: true
    uses: bitonality/RE-UE4SS/.github/workflows/build_ue4ss.yml@main
    secrets: inherit
    with:
      build-mode: ${{ matrix.mode }}
      commit-sha: ${{ github.sha }}
      should-upload-artifact: ${{matrix.artifact == true}}
      artifact-list: '{"UE4SS": ["target", "symbol"]}'
      artifact-retention-days: 14

  report-artifacts:
    name: "Report uploaded artifacts to pull requests"
    runs-on: ubuntu-latest
    needs: [ calculate_matrix, build ]
    steps:
      - uses: actions/github-script@v7
        id: generate-markdown
        with:
          result-encoding: string
          retries: 3
          script: |
            const artifacts = github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: ${{github.run_id}}
            });

            let artifactReport = ""

            for (const artifact of artifacts.data.artifacts) {
              artifactReport += `![badge](https://img.shields.io/badge/${artifact.name}Build_Success!-0d1117?style=for-the-badge&labelColor=3fb950&logo=data:image/svg%2bxml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI4MDAiIGhlaWdodD0iODAwIiB2aWV3Qm94PSIwIDAgNTEyIDUxMiI+PHBhdGggZD0iTTE5MiA5NmE2NCA2NCAwIDEgMC05NiA1NS4zOXYyMDkuMjJhNjQgNjQgMCAxIDAgNjQgMFYxNTEuMzlBNjQgNjQgMCAwIDAgMTkyIDk2Wm0tNjQtMzJhMzIgMzIgMCAxIDEtMzIgMzIgMzIgMzIgMCAwIDEgMzItMzJabTAgMzg0YTMyIDMyIDAgMSAxIDMyLTMyIDMyIDMyIDAgMCAxLTMyIDMyWk00MTYgMzYwLjYxVjE1NmE5Mi4xIDkyLjEgMCAwIDAtOTItOTJoLTIwVjMyYTE2IDE2IDAgMCAwLTI3LjMxLTExLjMxbC02NCA2NGExNiAxNiAwIDAgMCAwIDIyLjYybDY0IDY0QTE2IDE2IDAgMCAwIDMwNCAxNjB2LTMyaDIwYTI4IDI4IDAgMCAxIDI4IDI4djIwNC42MWE2NCA2NCAwIDEgMCA2NCAwWk0zODQgNDQ4YTMyIDMyIDAgMSAxIDMyLTMyIDMyIDMyIDAgMCAxLTMyIDMyWiIvPjwvc3ZnPg==)\n`;
              artifactReport += "|Name|Information|\n|---|---|\n";
              artifactReport += "|PR Commit | ${{github.event.pull_request.head.sha}} |\n";
              artifactReport += "| Merge Commit | ${{github.sha}} |\n";
              artifactReport += "| Logs | ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} |\n";
              artifactReport += `| Download Archive | ${artifact.archive_download_url} |\n`;
              artifactReport += `| Size | ${'BKMGT'[~~(Math.log2(artifact.size_in_bytes)/10)]} |\n`;
              artifactReport += `| Last Updated | ${artifact.updated_at} |\n`;
              artifactReport += `| Expires At | ${artifact.expires_at} |\n`;

              artifactReport += "\n\n";
            }

            return artifactReport;

      - name: Find possible previous comment
        if: ${{ startsWith(github.ref, 'refs/pull/')}}
        uses: peter-evans/find-comment@3eae4d37986fb5a8592848f6a574fdf654e61f9e
        id: findComment
        with:
          issue-number: ${{ github.event.number }}
          comment-author: 'github-actions[bot]'
          body-includes: '<!-- PR_ARTIFACTS -->'
      - name: Update comment
        if: ${{ startsWith(github.ref, 'refs/pull/')}}
        uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043
        with:
          comment-id: ${{ steps.findComment.outputs.comment-id }}
          issue-number: ${{ github.event.number }}
          body: |
            <!-- PR_ARTIFACTS -->
            ${{steps.generate-markdown.outputs.result}}
          edit-mode: replace
