name: "Build UE4SS Binaries"
permissions:
  contents: read
defaults:
  run:
    shell: pwsh
on:
  workflow_call:
    # Introduced 'inputs' to define parameters that can be passed when calling this workflow
    inputs:
      build-mode:
        description: 'Which UE4SS Mode to build. This is passed to xmake config -m <build-mode>'
        required: true
        type: string
      commit-sha:
        description: 
        type: string
      should-upload-artifact:
        description: 'Should build output be uploaded as an artifact?'
        default: false
        type: boolean
      artifact-list:
        description:
        default: '{"UE4SS": ["target", "symbol"]}'
        type: string
      artifact-retention-days:
        description:
        default: 14
        type: number
    outputs:
      artifact-url:
        description: "Directory where documents are generated."
        value: ${{ jobs.build.outputs.artifact-url }}
jobs:
  build:
    runs-on: windows-latest
    outputs:
      artifact-url: ${{ steps.upload-artifact.outputs.artifact-url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.UEPSEUDO_PAT }}
          ref: ${{inputs.commit-sha}}
        # Store the current week (00-53) to use as part of the xmake cache key.
        # This saves us from having to detect older caches and delete them.
      - name: Get current week as package key
        id: cache_key
        run: echo "key=$(date +'%W')" >> $GITHUB_OUTPUT
        shell: bash

      # Force xmake to a specific folder (for cache)
      - name: Set xmake env
        run: echo "XMAKE_GLOBALDIR=${{ runner.tool_cache }}/xmake-global" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Install VS2022 BuildTools 17.9.7
        run: choco install -y visualstudio2022buildtools --version=117.9.7.0 --params "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --installChannelUri https://aka.ms/vs/17/release/180911598_-255012421/channel"

      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: '2.9.2'

      - name: Update xmake repository
        run: xmake repo --update
      
      # Fetch xmake dephash
      - name: Retrieve dependencies hash
        id: dep_hash
        run: echo "hash=$(xmake l utils.ci.packageskey)" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append

      # Cache xmake dependencies
      - name: Restore cached xmake dependencies
        id: restore-depcache
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.XMAKE_GLOBALDIR }}/.xmake/packages
          # Example key: MSVC-Game__Shipping__Win64-42d5ac22284a460e96b6cab018d6b7b5-W23
          key: MSVC-${{ inputs.build-mode }}-${{ steps.dep_hash.outputs.hash }}-W${{ steps.cache_key.outputs.key }}

      # Setup compilation mode and install project dependencies 
      - name: Configure xmake and install dependencies
        run: |
          Import-Module 'C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\Common7\Tools\Microsoft.VisualStudio.DevShell.dll'
          Enter-VsDevShell -VsInstallPath 'C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools' -DevCmdArguments '-arch=x64 -host_arch=x64'

          xmake config -vD -m "${{inputs.build-mode}}" -y

      - name: Save cached xmake dependencies
        if: ${{ !steps.restore-depcache.outputs.cache-hit }}
        uses: actions/cache/save@v4
        with:
          path: ${{ env.XMAKE_GLOBALDIR }}/.xmake/packages
          key: ${{ steps.restore-depcache.outputs.cache-primary-key }}

      - name: Build
        id: build
        run: |
          xmake build -y

      - name: Calculate Files For Artifact Inclusion
        id: calc-files-artifact
        run: >
          $targets = ((xmake ci --dump=targets) | ConvertFrom-Json -AsHashtable)

          $artifacts = ('${{inputs.artifact-list}}' | ConvertFrom-Json -AsHashtable)

          $files_to_upload = @()

          foreach($i in $artifacts) {
            foreach($kvp in $i.GetEnumerator()) {
              $files_to_upload += ($targets[$kvp.Name][$kvp.Value])
            }
          }

          $artifact_dir = "${{runner.temp}}/ue4ss_artifacts/"

          foreach ($file in $files_to_upload) {
            Copy-Item "$file" -Destination (New-Item -Type Directory -Force "$artifact_dir")
          }

          echo "artifact_dir=$artifact_dir" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append

      - name: Upload a Build Artifact
        id: upload-artifact
        uses: actions/upload-artifact@v4.3.3
        if: ${{inputs.should-upload-artifact}}
        with:
          name: MSVC-${{inputs.build-mode}}-${{inputs.commit-sha}}
          path: |
                ${{ steps.calc-files-artifact.outputs.artifact_dir }}
          retention-days: ${{fromJSON(inputs.artifact-retention-days)}}
          overwrite: false