name: Build All Modes
permissions:
    contents: write
    pull-requests: write # For adding comments to PR.
on:
  pull_request:
    branches:
        - 'main'
    paths-ignore:
        - 'README.md'
        - 'docs/**'
        - 'docs-export/**'

# Ensure that rapid pushes to the pull request branch don't trigger this workflow multiple times.
# We only care about executing this workflow for that 'latest' commit on a PR.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Dynamically calculate which modes to build.
  calculate-matrix:
    name: Calculate job matrix
    runs-on: windows-2022
    outputs:
      matrix: ${{ steps.calculate-artifacts.outputs.result }} # JSON list of all modes.
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive # Clone the submodule so we can query xmake on the entire project.
          token: ${{ secrets.UEPSEUDO_PAT }}

        # Build modes are supplied by xmake, so we have to download and setup the xmake environment.
      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: "2.9.2"

        # `xmake ci --dump=modes` returns a JSON array of all UE4SS modes that xmake knows how to build.
      - name: Calculate the CI job matrix
        id: jobs
        shell: pwsh
        run: |
          $modes = (xmake ci --dump=modes)
          echo "all_modes=$modes" >> $env:GITHUB_OUTPUT
      - uses: actions/github-script@v7
        id: calculate-artifacts
        env:
          DEFAULT_MODES: '["Game__Debug__Win64","Game__Shipping__Win64"]'
          ALL_MODES: ${{steps.jobs.outputs.all_modes}}
        with:
          result-encoding: string
          retries: 3 # Retry in case REST requests fail transitively.
          script: |
            const { DEFAULT_MODES, ALL_MODES } = process.env
            const script = require('./.github/utils/calculate-modes-pull-request.js');
            return await script({context}, DEFAULT_MODES, ALL_MODES);

  # Build UE4SS for each mode we received from the `calculate_matrix` job.
  build:
    name: ${{ matrix.mode }}
    needs: [ calculate-matrix ] # Ensure the mode/artifact matrix has been generated before we launch this job.
    strategy:
      fail-fast: false # Disable fast failing because we want to cancel other modes if one fails.
      matrix: 
        # Use our generated matrix to populate the `include` array.
        include: ${{ fromJSON(needs.calculate-matrix.outputs.matrix) }}
    # Run our reusable workflow for each mode in our matrix.
    uses: ./.github/workflows/build_ue4ss.yml
    secrets: inherit # Inherit secrets from this workflow to safely pass `secrets.UE4SS_PAT` to our reusable workflow.
    with:
      build-mode: ${{ matrix.mode }}
      commit-sha: ${{ github.sha }} # This is the SHA of the PR merge result, not the HEAD of the PR branch!
      should-upload-artifact: ${{ matrix.artifact == true }}
      # JSON that declares what files to upload for specific xmake targets.
      # The supplied format should be compatible with the output of `xmake ci --dump=targets`.
      # This specifies that the `UE4SS` target should upload its target file and symbol file.
      # Ex. UE4SS.dll + UE4SS.pdb
      artifact-list: '{"UE4SS": ["target", "symbol"]}'
      artifact-retention-days: 14

  # This job fetches artifacts created in previous jobs.
  # It then reports these artifacts to the pull request that triggered this workflow.
  report-artifacts:
    name: "Report results to pull request"
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: npm install handlebars
        # We use GitHub's inline script step instead of defining our own JS/TypeScript action.
        # This avoids us having to take NPM dependencies in our repo.
        # We should consider implementing actions in an NPM project if the logic becomes too complex or unmaintainable. 
      - uses: actions/github-script@v7
        id: generate-markdown
        with:
          result-encoding: string
          retries: 3 # Retry in case REST requests fail transitively.
          script: |
            const script = require('./.github/utils/report-artifacts-to-pull-request.js');
            const handlebars = require('handlebars');
            return await script({github, context}, handlebars);

      # Update the existing PR artifact report comment if it already exists.
      - name: Find possible previous comment
        if: ${{ startsWith(github.ref, 'refs/pull/') && steps.generate-markdown.outputs.result}}
        uses: peter-evans/find-comment@3eae4d37986fb5a8592848f6a574fdf654e61f9e
        id: findComment
        with:
          issue-number: ${{ github.event.number }}
          comment-author: 'github-actions[bot]'
          body-includes: '<!-- PR_ARTIFACTS -->' # Hidden comment acts as an indicator that we've already commented on this PR. 
      - name: Update comment
        # Don't update the comment if we didn't generate any artifacts.
        if: ${{ startsWith(github.ref, 'refs/pull/') && steps.generate-markdown.outputs.result }}
        uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043
        with:
          comment-id: ${{ steps.findComment.outputs.comment-id }}
          issue-number: ${{ github.event.number }}
          body: |
            <!-- PR_ARTIFACTS -->
            ${{steps.generate-markdown.outputs.result}}
          edit-mode: replace
