name: Build All Modes
permissions:
    contents: write
    pull-requests: write # For adding comments to PR.
on:
  pull_request:
    branches:
        - 'main'
    paths-ignore:
        - 'README.md'
        - 'docs/**'
        - 'docs-export/**'

jobs:
  calculate_matrix:
    name: Calculate job matrix
    runs-on: windows-2022
    outputs:
      jobs: ${{ steps.jobs.outputs.jobs }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0 # needed to get commits since last tag
          token: ${{ secrets.UEPSEUDO_PAT }}
      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1.13.0

      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
      - name: Calculate the CI job matrix
        run: |
          $modes = (xmake ci --dump=modes) | ConvertTo-Json
          echo "jobs=$($modes | jq -cn --argjson modes $modes '$modes')" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
        id: jobs
        shell: powershell
  build:
    name: ${{ matrix.mode }}
    needs: [ calculate_matrix ]
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix: 
        mode: ${{ fromJSON(needs.calculate_matrix.outputs.jobs) }}
        include:
          - mode: "Game__Shipping__Win64"
            artifact: true
          - mode: "Game__Debug__Win64"
            artifact: true
    steps:
      - name: Build And Upload UE4SS
        id: build-ue4ss
        uses: ./.github/actions/msvc_build_ue4ss
        with:
          build-mode: ${{ matrix.mode }}
          commit-sha: ${{ github.sha }}
          should-upload-artifact: ${{matrix.artifact == true}}
          artifact-list: '{"UE4SS": ["target", "symbol"]}'
          artifact-retention-days: 14
      - name: Get Date
        id: get-date
        if: ${{ matrix.artifact == true && startsWith(github.ref, 'refs/pull/')}}
        shell: powershell
        run: |
          echo "date=$([DateTime]::UtcNow.ToString('u').Replace('Z','UTC'))" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
      - name: Find possible previous comment
        if: ${{ matrix.artifact == true && startsWith(github.ref, 'refs/pull/')}}
        uses: peter-evans/find-comment@3eae4d37986fb5a8592848f6a574fdf654e61f9e
        id: findComment
        with:
          issue-number: ${{ github.event.number }}
          comment-author: 'github-actions[bot]'
          body-includes: '<!-- PR_ARTIFACT_${{matrix.mode}} -->'
      - name: Update comment
        if: ${{ matrix.artifact == true && startsWith(github.ref, 'refs/pull/')}}
        uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043
        with:
          comment-id: ${{ steps.findComment.outputs.comment-id }}
          issue-number: ${{ github.event.number }}
          body: |
            <!-- PR_ARTIFACT_${{matrix.mode}} -->
            ![badge]
            
            You can find a link to your latest successful build below.
            
            | Name | Link |
            | --- | --- |
            | Commit | ${{ github.sha }} |
            | Logs | ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} |
            | Download | ${{ steps.build-ue4ss.outputs.artifact-url }} |
            | Time | ${{ env.DATE }} |
            
            [badge]: https://img.shields.io/badge/${{matrix.mode}}_Build_Success!-0d1117?style=for-the-badge&labelColor=3fb950&logo=data:image/svg%2bxml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI4MDAiIGhlaWdodD0iODAwIiB2aWV3Qm94PSIwIDAgNTEyIDUxMiI+PHBhdGggZD0iTTE5MiA5NmE2NCA2NCAwIDEgMC05NiA1NS4zOXYyMDkuMjJhNjQgNjQgMCAxIDAgNjQgMFYxNTEuMzlBNjQgNjQgMCAwIDAgMTkyIDk2Wm0tNjQtMzJhMzIgMzIgMCAxIDEtMzIgMzIgMzIgMzIgMCAwIDEgMzItMzJabTAgMzg0YTMyIDMyIDAgMSAxIDMyLTMyIDMyIDMyIDAgMCAxLTMyIDMyWk00MTYgMzYwLjYxVjE1NmE5Mi4xIDkyLjEgMCAwIDAtOTItOTJoLTIwVjMyYTE2IDE2IDAgMCAwLTI3LjMxLTExLjMxbC02NCA2NGExNiAxNiAwIDAgMCAwIDIyLjYybDY0IDY0QTE2IDE2IDAgMCAwIDMwNCAxNjB2LTMyaDIwYTI4IDI4IDAgMCAxIDI4IDI4djIwNC42MWE2NCA2NCAwIDEgMCA2NCAwWk0zODQgNDQ4YTMyIDMyIDAgMSAxIDMyLTMyIDMyIDMyIDAgMCAxLTMyIDMyWiIvPjwvc3ZnPg==
          edit-mode: replace
        env:
          DATE: "${{ steps.get-date.outputs.date}}"
